---
- name: create dir
  file:
    path: ~/.ssh
    mode: 0700
    state: directory
- name: touch authorized_keys file
  lineinfile:
    create: yes
    state: present
    path: ~/.ssh/authorized_keys
    mode: 0600
    line: "{{ pub_key }}"