---
- name: set host mac address
  set_fact:
    host_mac_address: "{{ hostvars[inventory_hostname].ansible_default_ipv4.macaddress}}"
- name: set vars
  set_fact:
    kube_ip_address: "{{ mac_mapping[host_mac_address].ip }}"
    kube_hostname: "{{ mac_mapping[host_mac_address].name }}"

- name: print vars from mac > IP/Hostname mapping
  debug:
    msg: 
      - "IP: {{ kube_ip_address }}" 
      - "Hostname: {{ kube_hostname }}"

- name: update hosts file
  template:
    dest: "{{ item.dest_file }}"
    src: "{{ item.src_file }}"
    owner: root
    group: root
    mode: 644
  loop:
    - { src_file: './inventory/templates/hosts.j2', dest_file: '/etc/hosts' }
    - { src_file: './inventory/templates/interfaces.j2', dest_file: '/etc/network/interfaces' }
    - { src_file: './inventory/templates/hostname.j2', dest_file: '/etc/hostname' }
    - { src_file: './inventory/templates/resolv.conf.j2', dest_file: '/etc/resolv.conf' }
  notify: reboot_host


# - name: deploy interfaces file
#   template:
#     dest: /etc/network/interfaces
#     src: ./inventory/templates/interfaces.j2
#     owner: root
#     group: root
#     mode: 644
#gather_facts: yes
#become: yes
#become_user: root